
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 250  
#200 - sale cada 5
#250 - sale cada 4
  
  # Position Controllers ---------------------------------------
  arm_1_joint:
    type: effort_controllers/JointPositionController
    joint: arm_1_joint
    pid: {p: 50.0, i: 0.1, d: 1.0}
  arm_2_joint:
    type: effort_controllers/JointPositionController
    joint: arm_2_joint
    pid: {p: 50.0, i: 0.1, d: 1.0}
  arm_3_joint:
    type: effort_controllers/JointPositionController
    joint: arm_3_joint
    pid: {p: 50.0, i: 0.1, d: 1.0}
  arm_4_joint:
    type: effort_controllers/JointPositionController
    joint: arm_4_joint
    pid: {p: 10.0, i: 0.0, d: 0.0}
  arm_5_joint:
    type: effort_controllers/JointPositionController
    joint: arm_5_joint
    pid: {p: 10.0, i: 0.1, d: 0.0}
  gripper_1_joint:
    type: effort_controllers/JointPositionController
    joint: gripper_1_joint
    pid: {p: 10.0, i: 0.1, d: 1.0}
    
    


